declare const styles: {
  readonly projcard: string;
  readonly projcardBar: string;
  readonly projcardBorder: string;
  readonly projcardCodepen: string;
  readonly projcardCodepenWhite: string;
  readonly projcardDescription: string;
  readonly projcardGradient: string;
  readonly projcardImg: string;
  readonly projcardImgDarker: string;
  readonly projcardImgWrapper: string;
  readonly projcardInnerbox: string;
  readonly projcardNoise: string;
  readonly projcardRight: string;
  readonly projcardLink: string;
  readonly projcardSubtitle: string;
  readonly projcardTag: string;
  readonly projcardTagbox: string;
  readonly projcardTextbox: string;
  readonly projcardTitle: string;
};
export = styles;
